### ISSUE TITLE
attachAllPermissions

### ISSUE THREAD

**Issue by caize** [3amprogrammer/phalcon-roles#1]
$array = [1,2,3];
        $permissions = Permission::find(
            [
                'id IN ({id:array})',
                'bind' => [
                    'id' => $array
                ]
            ]
        );
        $role = Role::findFirst();
        $role->getPermissions();
        $role->attachAllPermissions($permissions);
        Error : 'attachAllPermissions() must be of the type array, object given'

**Comment by 3amprogrammer** [comment]
Well, this is one of the many things I trully hate about Phalcon - inconsistency. When you fetch stuff you get Resultset, when you put your stuff into relation property you must provide an array.

To set permissions I have decided, that `attachAllPermissions` would accept an **array of Permissions** (`Permission[]`, I think it's even typehinted).

`Permission::find` returns an object of type ResultsetInterface.  I would add a support for this later, but for now you can just do:
```
$permissionsToAdd = $permissions->filter(function(Permission $permission) {
    return $permissions; 
});
```

@Edit 
It should work now :)
https://github.com/3amprogrammer/phalcon-roles/commit/e192811845e33e6232ee37bc0fa5bf805532fd2b
